# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_card',
                'doc_host': 'https://ballou88.github.io',
                'git_url': 'https://github.com/ballou88/nbdev_card',
                'lib_path': 'nbdev_card'},
  'syms': {'nbdev_card.core': {'nbdev_card.core.foo': ('core.html#foo', 'nbdev_card/core.py')}}}
