"""A simple API for creating and using playing cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 2
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 4
suits = ["♣️","♦️","❤️","♠️"]
ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb 13
class Card:
    "A Playing card"
    def __init__(self, suit:int, rank:int):
        self.suit,self.rank = suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__
    

# %% ../nbs/00_card.ipynb 18
@patch
def __eq__(self:Card, a:Card): return (self.suit, self.rank) == (a.suit, a.rank)

# %% ../nbs/00_card.ipynb 20
@patch
def __lt__(self:Card, a:Card): return (self.suit, self.rank) < (a.suit, a.rank)

# %% ../nbs/00_card.ipynb 22
@patch
def __gt__(self:Card, a:Card): return (self.suit, self.rank) > (a.suit, a.rank)
